### ISSUE TITLE
This make function Math.random() in my whole react app return 0.5

### ISSUE THREAD

**Issue by lPaths** [davidhu2000/react-spinners#109]
**Describe the bug**
These LOC from GridLoader.js make every function Math.random() in my react app return 0.5![image](https://user-images.githubusercontent.com/22215743/63542972-e400fd80-c54b-11e9-9bf7-6de99f050ca0.png)

**To Reproduce**

**Expected behavior**
This line of code only affects Math.random() in component scope

**Screenshots**
![image](https://user-images.githubusercontent.com/22215743/63542770-59b89980-c54b-11e9-856c-765afdc1d4ac.png)

![image](https://user-images.githubusercontent.com/22215743/63542792-6b01a600-c54b-11e9-9caa-4c1224fd5bb9.png)

**Additional context**

**Comment by davidhu2000** [comment]
oh oops, that is suppose to be in the tests. I'll get this fixed.

**Comment by lPaths** [comment]
> oh oops, that is suppose to be in the tests. I'll get this fixed.

thank you :D

**Comment by davidhu2000** [comment]
@lPaths can you update to `v0.6.1` and see if your issue is resolved?

**Comment by lPaths** [comment]
> @lPaths can you update to `v0.6.1` and see if your issue is resolved?

The problem is fixed, ty
