### ISSUE TITLE
FadeLoader prop radius  is not changing radius of the loader

### ISSUE THREAD

**Issue by Dwlad90** [davidhu2000/react-spinners#126]
`<FadeLoader
          color='white'
          radius={5}
          height={10}
          width={3}
          margin="5px"
        />`

![Screen Shot 2019-10-12 at 14 21 20](https://user-images.githubusercontent.com/22377836/66700654-9dce4c00-ecfb-11e9-8ec4-55b67046dd8b.png)

**Comment by roberts98** [comment]
Hello @Dwlad90 
Actually the border radius is being set correctly, but because you have such a small width you don't see the radius, try setting the width to e.g 10, and you'll se the dot, instead of square, meaning that radius is working correctly.

**Comment by davidhu2000** [comment]
that is correct. closing this issue.

**Comment by Dwlad90** [comment]
![Screen Shot 2019-10-26 at 20 42 39](https://user-images.githubusercontent.com/22377836/67623717-3fdc5100-f831-11e9-9705-78ce55af9c80.png)
![Screen Shot 2019-10-26 at 20 42 32](https://user-images.githubusercontent.com/22377836/67623718-3fdc5100-f831-11e9-99f7-9b47f2db00f7.png)
![Screen Shot 2019-10-26 at 20 42 22](https://user-images.githubusercontent.com/22377836/67623719-4074e780-f831-11e9-9210-7ca1a2b878eb.png)
![Screen Shot 2019-10-26 at 20 42 12](https://user-images.githubusercontent.com/22377836/67623720-4074e780-f831-11e9-9133-1d1ab0cd2c09.png)

But example on your site don't work correctly.
