### ISSUE TITLE
Move 'emotion' package to full dependency

### ISSUE THREAD

**Issue by jcheroske** [davidhu2000/react-spinners#13]
Getting an error using any component that's dependent on the `emotion` package. I think it needs to be moved to a full dependency.

**Comment by GuillaumeCisco** [comment]
What is the error?

**Comment by jcheroske** [comment]
Wow, I wrote a horrible bug report! Sorry about that.

The error we're running into is a 'Package not found' error on the `emotion` package, when we try and use `react-spinners`. I looked at the transpiled code, and saw that the various spinners are requiring the `emotion` package, but when I checked `package.json`, I saw that it was only listed as a `devDependency`. Shouldn't it be a full `dependency`?

**Comment by GuillaumeCisco** [comment]
Hum, so, the moment you ran `npm install emotion@7.2.0`, it worked?

**Comment by jcheroske** [comment]
Yes, that's correct. Looking at your code, I'm really curious how the `emotion` import can work without it being a `dependency`:

`/src/spinners/BarLoader`
```
import React from 'react';
import PropTypes from 'prop-types';
import { keyframes, css } from 'emotion'; // <-- I don't get this when installing react-spinners
import { onlyUpdateForKeys } from 'recompose';
import { calculateRgba } from '../helpers';
```
