### ISSUE TITLE
Use '<span>' instead of '<div>'

### ISSUE THREAD

**Issue by olive007** [davidhu2000/react-spinners#159]
Simply change div to span inside the code to be able to use it inside text element.

**Problem related:**
We got a warning if we want to any loader inside a text element (\<p/>).
> Warning: validateDOMNesting(...): \<div> cannot appear as a descendant of \<p>.

**Comment by 0xc0d3r** [comment]
Hi @olive007 

As per [HTML5 spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element), using a block element `div` inside of `p` is invalid. For more details check [here](https://stackoverflow.com/questions/10763780/putting-div-inside-p-is-adding-an-extra-p)

I hope you understand the problem.

**Comment by jaketoolson** [comment]
@0xc0d3r this is why Olive007 is suggesting replacing div with span.

**Comment by davidhu2000** [comment]
I will look into this. Hopefully this could be an easy switch and wouldn't cause any major styling issues.

**Comment by davidhu2000** [comment]
@olive007 can you install `react-spinners@0.10.0-alpha.3` and see if this issue is resolved?
