### ISSUE TITLE
Library does not support tree shaking

### ISSUE THREAD

**Issue by knpwrs** [davidhu2000/react-spinners#188]
**Describe the bug**

I'm getting ready to launch an app to production and decided to use [`webpack-bundle-analyzer`](https://www.npmjs.com/package/webpack-bundle-analyzer) to see if I could cut down on my bundle size. To my surprise, even though I only included one spinner in one location, I found that all of the spinners were being bundled into my app.

**To Reproduce**

Build a project importing a single spinner from this package and analyze the bundle with `webpack-bundle-analyzer`.

**Expected behavior**

The package should be tree-shakable in order to minimize bundle size.

**Screenshots**

`import { PulseLoader } from 'react-spinners'`:

![image](https://user-images.githubusercontent.com/174864/80913424-834cd600-8d12-11ea-83b8-8555fd9c7100.png)

`import PulseLoader from 'react-spinners/PulseLoader'`:

![image](https://user-images.githubusercontent.com/174864/80913498-040bd200-8d13-11ea-841c-a80d45a285b9.png)

**Suggestions**

1. Ship an esmodule and set the `module` field in `package.json`
1. Use `export { default as PulseLoader } from './PulseLoader'` for each spinner instead of importing then exporting them all in `index.ts`
1. Denote any side effects in the package: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by davidhu2000** [comment]
@knpwrs thanks for that, i'll look into this. In the meantime, you can do this to only import one loader

```
import PulseLoader from 'react-spinners/PulseLoader';
```

**Comment by davidhu2000** [comment]
@knpwrs can you install `react-spinners@0.10.0-alpha.3` and see if this issue is resolved?

**Comment by davidhu2000** [comment]
Look like that PR did it. 

According to [bundlephobia](https://bundlephobia.com/result?p=react-spinners@0.10.0-beta.3)

<img width="655" alt="Screen Shot 2020-12-29 at 11 04 39 PM" src="https://user-images.githubusercontent.com/15827041/103335602-42849880-4a2a-11eb-91e7-64b11ff2141b.png">
