### ISSUE TITLE
using Hook instead of class  

### ISSUE THREAD

**Issue by kyle-hensoon** [davidhu2000/react-spinners#189]
upddate package with functional component

**Comment by davidhu2000** [comment]
can you add more details regarding the benefit of doing that versus the current setup?

**Comment by PierreMarieRiviere** [comment]
For those of us coding with hooks and not learning legacy React. Documentation should be updated.

**Comment by davidhu2000** [comment]
https://github.com/davidhu2000/react-spinners#example

example has been updated using react hooks.
