### ISSUE TITLE
Spinner broken, CSS styles missing in production

### ISSUE THREAD

**Issue by Slind14** [davidhu2000/react-spinners#20]
Hi there,
I'm using meteor and when deploying to production some of the CSS styles are missing while they are all there in development. I assume that this is due to emotion's pre compiling the css. e.g. the `border-radius` from the RingLoader:

![](https://i.imgur.com/9Bag7I1.png)

Since this is a react library I am wondering: What is the reason for emotion?
According to this benchmark it is even slower than reacts CSS inline functionality.
https://github.com/A-gambit/CSS-IN-JS-Benchmarks/blob/master/RESULT.md

**Comment by Slind14** [comment]
oO this might be fixed, I'll test tomorrow.
https://github.com/davidhu2000/react-spinners/commit/648c2de6756fc56f6f97a791122cb5c5b331c2ff#diff-2ff1847bd31d2b5abae61ec6ba6db73c

Might I ask why emotion, still?

**Comment by davidhu2000** [comment]
#5 should offer some clarity. It was implemented to allow Server Side Rendering. It was suggested to me as a solution. I welcome any suggestions if you have a better on how to handle SSR.

**Comment by Slind14** [comment]
Ahh, I didn't think about this limitation. This can be worked around by creating/injecting a script block.
e.g. https://gist.github.com/yamadayuki/f1ea9ccacad7f1c140457b5877fb54cc
https://codepen.io/mosson/pen/zGENPx

**Comment by davidhu2000** [comment]
👍  closing this issue now
