### ISSUE TITLE
NPM run watch script fails in Windows bash

### ISSUE THREAD

**Issue by dsaw** [davidhu2000/react-spinners#207]
**Describe the bug**
When trying to run the `npm run watch` command after setting up the repo, it fails on Windows bash terminal.

**To Reproduce**
1. Checkout repo locally
2. Follow the build instructions as given in the file
3. Run `npm run watch`
4. It fails while running `babel-node` command with error `SyntaxError: missing ) after argument list`

**Screenshots**
![runwatch_babelfails](https://user-images.githubusercontent.com/5353891/85230823-798d4800-b410-11ea-9f6b-6141dce36ad4.PNG)

It seems like the process is interpreting the script as a _js_ file. There are open issues in other repos like [here](https://github.com/mozilla/fxa/issues/3713) where the same thing happens. Currently, a workaround is to replace the webpack script directory with the one in `node_modules` as given in the `package.json` script definitions.
```
  "watch": "babel-node ./node_modules/webpack/bin/webpack --watch --config ./webpack.config.dev.js"
```

**Comment by davidhu2000** [comment]
can you check if this still happens in the latest version? going to close for now
