### ISSUE TITLE
MoonLoader visual rendering bug

### ISSUE THREAD

**Issue by istratievladut** [davidhu2000/react-spinners#21]
Hello,
I just updated the library from 0.0.30 to the last version and I noticed that the MoonLoader does not have the same animation and it seems to me like a bug.
Here is a screenshot with what I see.
<img width="203" alt="screen shot 2017-12-13 at 10 44 00" src="https://user-images.githubusercontent.com/25583466/33930087-6b5ccfc8-dff4-11e7-9c8d-7a97b62088ab.png">

This rectangle is just spinning around.

**Comment by davidhu2000** [comment]
This is fixed in `v0.3.2`
