### ISSUE TITLE
width 100%

### ISSUE THREAD

**Issue by brunobraga** [davidhu2000/react-spinners#27]
I'd like to set a BarLoader for example with width:100%.
Although it still works, the console throws the following error/warning message:
`Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `Loader`, expected `number`.
    in Loader (created by onlyUpdateForKeys(Loader))`

Example:

`
<RingLoader
          width={'100%'} 
          loading={this.state.loading} 
        />
`

It would be great if this does not throw a warning, or another property would allow for that.

Thanks,

**Comment by wesbos** [comment]
👍🏻 Please merge this
