### ISSUE TITLE
PulseLoader generates unique "key" prop console errors

### ISSUE THREAD

**Issue by chiubaka** [davidhu2000/react-spinners#293]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1732408/100198549-efa15800-2f36-11eb-892b-f118b65f1dfa.png)

`PulseLoader` appears to be generating unique "key" prop errors. We're using `react-spinners@0.9.0`.

**To Reproduce**
1. Render a PulseLoader anywhere...

**Expected behavior**
No unique "key" prop errors--clear console and keys defined on individual PulseLoader elements.

**Screenshots**

**Additional context**

**Comment by chiubaka** [comment]
Notably: This doesn't seem to be an issue once the bundle is built and deployed. But it does show up when developing locally using `webpack-dev-server`.

**Comment by davidhu2000** [comment]
@chiubaka can you share a minimal reproducible example? I'm unable to reproduce this issue.

```
import './App.css';
import PulseLoader from 'react-spinners/PulseLoader'

function App() {
  return (
    <div className="App">
      <PulseLoader />
    </div>
  );
}

export default App;
```

this runs fine without any concern errors. I generated this using create-react-app. 



> Notably: This doesn't seem to be an issue once the bundle is built and deployed. But it does show up when developing locally using `webpack-dev-server`.

as for this, it makes sense. Production built strips a ton of this out.

**Comment by davidhu2000** [comment]
i think this issue should be resolved since emotion is removed. please reopen if it still doesn't work.
