### ISSUE TITLE
react-spinners@0.9.0 incompatible with react@17.0.1

### ISSUE THREAD

**Issue by EbenBosman** [davidhu2000/react-spinners#321]
I am attempting to update the dependencies of the project I am working on. However it seems that react-spinners@0.9.0 (Latest version as of writing) is incompatable with react@17.0.1. Please the output of `npm install` below:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: xxxxxx@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-spinners@0.9.0
npm ERR! node_modules/react-spinners
npm ERR!   react-spinners@"^0.9.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by mlippert** [comment]
Interesting. I see:
```
npm WARN react-spinners@0.9.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-spinners@0.9.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
```
But everything still works. I'm running npm version `6.14.10` and node version `v12.20.0` in case that may matter.

Since everything still works w/ react and react-dom `v17` it'd be nice if the react-spinners peer dependency version was updated to reflect that (unless there are problems I just haven't encountered).

**Comment by T0X1CCAT** [comment]
not sure if this is related, but I am on react 17.0.1 and I see a spinner but it doesn't look like the one I specified, and it does not change if I select different react spinners. Just a circle sort of pulsing

**Comment by davidhu2000** [comment]
should be a fairly easy fix. https://github.com/davidhu2000/react-spinners/blob/master/package.json#L92-L93

need to add v17 into peer dependencies

**Comment by davidhu2000** [comment]
@EbenBosman can you install `react-spinners@0.10.0-alpha.3` and see if this issue is resolved?

**Comment by T0X1CCAT** [comment]
> @EbenBosman can you install `react-spinners@0.10.0-alpha.3` and see if this issue is resolved?

i believe the issue is fixed
