### ISSUE TITLE
 Must use import to load ES Module: node_modules/react-spinners/SyncLoader.js

### ISSUE THREAD

**Issue by tyteen4a03** [davidhu2000/react-spinners#336]
I'm getting this error when using 0.10.1 of this package:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: **/node_modules/react-spinners/SyncLoader.js
require() of ES modules is not supported.
require() of **/node_modules/react-spinners/SyncLoader.js from **/.next/server/pages/**.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename SyncLoader.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from **react-spinners/package.json.

    at new NodeError (node:internal/errors:278:15)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at eval (webpack-internal:///react-spinners/SyncLoader:1:18)
    at Object.react-spinners/SyncLoader (**/.next/server/pages/**.js:820:1)
    at __webpack_require__ (**/.next/server/pages/**.js:23:31)
    at eval (webpack-internal:///./pages/**.tsx:6:83) {
  code: 'ERR_REQUIRE_ESM'
}
```

No such error with 0.9.0.

**Comment by davidhu2000** [comment]
Can you provide some code samples to reproduce this issue? 

I generated a blank react app and was able to run it without issues

**Comment by davidhu2000** [comment]
@tyteen4a03 are you doing something like
```
const SyncLoader = require('react-spinners/SyncLoader');
```
instead of 

```
import SyncLoader from 'react-spinners/SyncLoader'
```
?

can you share the packages involved in your app so I can better reproduce it and see if I can create a fix? As far as I know, most people uses the `import` syntax.

**Comment by davidhu2000** [comment]
@tyteen4a03, I found an issue with 0.10.1 and deprecated it. The `type: module` is still in `package.json`, so I'm not sure if my fix is related to your issue. But can you try 0.10.2 and see if you still see the issue?

**Comment by tyteen4a03** [comment]
@davidhu2000 I used to do `import { SyncLoader } from 'react-spinners'. `import SyncLoader from 'react-spinners/SyncLoader` triggers the same issue.

I'll try 0.10.2.

**Comment by tyteen4a03** [comment]
Unfortunately same issue: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: **/react-spinners/SyncLoader.js` with `import SyncLoader from 'react-spinners/SyncLoader'`

**Comment by MariusAlch** [comment]
Same issue.

**Comment by EricKit** [comment]
> @tyteen4a03, I found an issue with 0.10.1 and deprecated it. The `type: module` is still in `package.json`, so I'm not sure if my fix is related to your issue. But can you try 0.10.2 and see if you still see the issue?

I'm having this issue running NextJS for some background. In 0.10.2 there is still `type: module` in the package.json.

**Comment by davidhu2000** [comment]
I still can't reproduce it using create react app. In the meantime, I'll revert #327 for now, and publish a new patch. 

Can someone please provide some actual code to help me reproduce?

**Comment by davidhu2000** [comment]
this is done. Can you try `0.10.4` and see if this issue is fixed?

**Comment by EricKit** [comment]
> this is done. Can you try `0.10.4` and see if this issue is fixed?

0.10.4 works. 

To reproduce the issue set-up a NextJS environment:

`npx create-next-app`
Name it whatever you want, go into the folder.

Add to `package.json` 
`"react-spinners": "0.10.2"`

Add to `pages/index.js`

`import MoonLoader from "react-spinners/MoonLoader";`

And in the return anywhere add `<MoonLoader></MoonLoader>`

This will create your issue, I just tested it.

**Comment by tyteen4a03** [comment]
Thanks - looks like 0.10.4 fixed things.
