### ISSUE TITLE
Moon Spinner broken animation

### ISSUE THREAD

**Issue by benji-meldcx** [davidhu2000/react-spinners#340]
**Describe the bug**
The larger circle of the moon spinner is incorrectly spinning.

**To Reproduce**
1. Go to the [demo page](https://www.davidhu.io/react-spinners)
2. View the Moon Spinner
3. Observe the outer circle spins when it should remain still

**Expected behavior**
Outer circle should remain still.

**Screenshots**
<image src="https://user-images.githubusercontent.com/69223225/103490896-0494d380-4e73-11eb-8cd2-6f8d7afd7194.gif" width="400" />

**Comment by davidhu2000** [comment]
Fixed in 0.10.5
