### ISSUE TITLE
Problem with MoonLoader

### ISSUE THREAD

**Issue by doppelgunner** [davidhu2000/react-spinners#36]
The whole body is rotating together with the little thing lol. please fix this I like the moon loader above all.
![Moonloader bug](https://i.imgur.com/4S8BhM5.gif)

**Comment by davidhu2000** [comment]
@doppelgunner can you provide more details? Like what version you are using? 

Can you publish your `package.json`?

**Comment by GuillaumeCisco** [comment]
@doppelgunner Looks like you have a css that is overridding your loader, try investigating on `position` css attributes on parents.

**Comment by drewandre** [comment]
I'm also seeing this... I can't find any computed css that would be overridding the loader. 
<img width="275" alt="screen shot 2018-07-26 at 4 43 31 pm" src="https://user-images.githubusercontent.com/13245041/43287447-1921c4e2-90f3-11e8-8afe-96c7bb869071.png">

**Comment by GuillaumeCisco** [comment]
@drewandre Can you provide a project example maybe?
Otherwise, inspect the code on http://www.davidhu.io/react-spinners/ for the moon loader and look a the `position` css attributes. Maybe wrapping the loader with a css position will make it works correctly.
It will allow us to detect the undesired behavior.
Thank you,

**Comment by jfremy** [comment]
I ran into the same issue. In my case, it was due to the "box-sizing" property being set to "border-box" for all divs in the CSS (defined in the theme I use).
I used a className css that sets it to "content-box" when calling MoonLoader and this fixed the issue for me

**Comment by NamorNimash** [comment]
Have the same issue with Moonloader. For example, Cliploader work perfectly in the parent.

**Comment by GRMCosta** [comment]
Put display: flex works for my. Example:

`import MoonLoader from "react-spinners/MoonLoader";
import { css } from "@emotion/react";


const override = css`
  display: flex;
  margin: 0 auto;
  border-color: red;
`;

export function Loading() {
    return (
            <MoonLoader color={"#000"} css={override} size={50} />
    )
}`

**Comment by Fin-Alan** [comment]
same issue for me
i also tried box-content 
it did not work

**Comment by RigoOnRails** [comment]
@teebszet @Fin-Alan Hey guys, I believe this is the issue you were dealing with: https://github.com/davidhu2000/react-spinners/issues/583
