### ISSUE TITLE
MoonLoader doesn't spin

### ISSUE THREAD

**Issue by Samuel-Montoya** [davidhu2000/react-spinners#387]
**Describe the bug**
MoonLoader is not rendered like it should.
Latest version of React.

**To Reproduce**
1. Import MoonLoader `import MoonLoader from "react-spinners/MoonLoader"`
2. Render in JSX `<MoonLoader size={50} />`

3. See error

<img width="167" alt="Screen Shot 2021-03-16 at 5 04 26 PM" src="https://user-images.githubusercontent.com/34517166/111391230-cb9a8b80-8679-11eb-9cfb-4f64b8e585b2.png">

**Additional context**
NPM Version: ^0.10.6
React Version: ^17.0.1
Other loaders seem to work properly.

**Comment by YEK-PLUS** [comment]
can you share your parent component with css?

**Comment by Samuel-Montoya** [comment]
> can you share your parent component with css?

```
<div style={{ display: 'table', margin: 'auto' }}>
	<MoonLoader color="white" size={15} />{' '}
</div>
```

**Comment by YEK-PLUS** [comment]
@Samuel-Montoya try [this](https://codesandbox.io/s/react-spinners387-jtx1i?file=/src/App.js) 

```js
<div style={{ display: "flex" }}>
   <MoonLoader size={32} />
</div>
```

**Comment by Samuel-Montoya** [comment]
> @Samuel-Montoya try [this](https://codesandbox.io/s/react-spinners387-jtx1i?file=/src/App.js)
> 
> ```js
> <div style={{ display: "flex" }}>
>    <MoonLoader size={32} />
> </div>
> ```

Hmm, No luck.. It seems to be spinning with the outer circle. Maybe it's because I have it nested in a `<button>` tag?

<img width="333" alt="Screen Shot 2021-04-27 at 3 12 27 PM" src="https://user-images.githubusercontent.com/34517166/116313496-13c5c700-a76b-11eb-8a63-739a7b27afd4.png">
<img width="318" alt="Screen Shot 2021-04-27 at 3 12 33 PM" src="https://user-images.githubusercontent.com/34517166/116313501-145e5d80-a76b-11eb-8ae5-6d9d2d9b411e.png">

**Comment by hkar19** [comment]
i find it is weird that if i put the moonloader in a flexbox, the moonloader rotates with the center in the white part of the moonloader

such as

```js
<div style={{display:'flex', justifyContent:'center', alignItems:'center'}}>
  <MoonLoader
    color={'#fff'}
   loading={true}
  />

</div>
```

**Comment by davidhu2000** [comment]
can you share all the relevant computed CSS and your jsx used to render? I'm not really seeing the issue.

**Comment by hkar19** [comment]
this is [sandbox](https://codesandbox.io/s/nostalgic-moon-35ws5?file=/src/App.js) for my issue

**Comment by YEK-PLUS** [comment]
@hkar19 
add `textAlign: "left"` to line 17
this is [sandbox](https://codesandbox.io/s/red-cookies-ekclh?file=/src/App.js)

**Comment by hkar19** [comment]
> @hkar19 
> add `textAlign: "left"` to line 17
> this is [sandbox](https://codesandbox.io/s/red-cookies-ekclh?file=/src/App.js)

Right! That could be a workaround id your `MoonLoader` does not rotate

**Comment by keithfrazier98** [comment]
I just came across the same issue with the moon loader with this code: 

```
<div className="pr-3 flex flex-row items-center">
   {`${pending} Pending`}
   <div className="ml-2 w-5 h-5">
      <MoonLoader size="24px" color="#f3c429" />
  </div>
</div>
```

I was able to fix it by rendering the Moonloader alone without inhibiting its container, and just adding styling to the test on the left of it:

```
<div className="flex flex-row items-center">
   <p className="mr-2">{`${pending} Pending`}</p>
    <MoonLoader size="15px" color="#f3c429" />
</div>{" "}
```

Which seems like the better way to have coded that in the first place.

**Comment by davidhu2000** [comment]
sounds like we have a implementation, so going to close this for now
