### ISSUE TITLE
widthUnit prop is not documented

### ISSUE THREAD

**Issue by jacargentina** [davidhu2000/react-spinners#39]
I've found about it (for giving 100% width to a BarLoader) by looking at the sources. Should be added to the Readme.md at least!

**Comment by shoudou** [comment]
I could not find how to get my RingLoader to cover the whole page instead of sticking a the top left corner of the page only. Do you have any idea, Jacargentina? Thanks

**Comment by davidhu2000** [comment]
This is fixed in 0.4.3
