### ISSUE TITLE
Upgrade to 0.11 fails - Module not found: Error: Can't resolve '@emotion/core'

### ISSUE THREAD

**Issue by tonydehnke** [davidhu2000/react-spinners#425]
**Describe the bug**
(Newbie here)

When dependabot ran today - it tried to upgrade react-spinners from 0.10.6 to 0.11.0.

CI testing failed with an error:  Module not found: Error: Can't resolve '@emotion/core'

I googled it and found this in another repo:  https://github.com/projectstorm/react-diagrams/issues/783

_"Apparently in Emotion 11, @emotion/core was renamed to @emotion/react,"_

It seems like maybe the dependancies for react-spinners need to be updated or changed so that the right ones are installed?

`ERROR in ./app/javascript/components/EventsFormScheduler.tsx
Module not found: Error: Can't resolve '@emotion/core' in '/home/circleci/project/app/javascript/components'
 @ ./app/javascript/components/EventsFormScheduler.tsx 20:0-36 130:9-12
 @ ./app/javascript/components/EventsForm.tsx
 @ ./app/javascript/components/Editor.tsx
 @ ./app/javascript/components/Scheduler.tsx
 @ ./app/javascript/components/App.tsx
 @ ./app/javascript/packs/index.tsx`

Expected Behaviour:
   - Upgrade should work, or changelog should indicate Breaking Change

**Comment by AwolDes** [comment]
Getting a similar problem with react 17& v0.11 of spinners - https://github.com/davidhu2000/react-spinners/issues/430#issuecomment-873717462

**Comment by davidhu2000** [comment]
hmm, that's strange, I don't see any reference to `@emtion/core` in this codebase. are you able to share some more code to help reproduce?

**Comment by davidhu2000** [comment]
the PR to rename to @emotion/react https://github.com/davidhu2000/react-spinners/pull/329/files

**Comment by davidhu2000** [comment]
this issue should be resolved in 0.13.0 as emotion is getting removed, see #208 and #474 for more details
