### ISSUE TITLE
Tests failing because called `mount()` without a global document

### ISSUE THREAD

**Issue by Seth10001** [davidhu2000/react-spinners#455]
**Describe the bug**
The tests are currently failing on master with the following error:

```
Test suite failed to run

    It looks like you called `mount()` without a global document being loaded.
```

**To Reproduce**

1. npm run jest

**Comment by davidhu2000** [comment]
probably need to get rid of enzyme and replace with RTL

**Comment by davidhu2000** [comment]
closing this in favor of #472
