### ISSUE TITLE
Can't Install Package

### ISSUE THREAD

**Issue by Fosol** [davidhu2000/react-spinners#457]
`npm install react-spinner` fail to find the package

Error = `Not Found - GET https://registry.npmjs.org/@types%2freact-spinners - Not found`

`yarn add react-spinner` fail to find the package.

Error = `An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-spinners: Not found`

**To Reproduce**

Node Version: v16.10.0
NPM Version: 7.24.0
Yarn Version: 1.22.5

1. Try to install the package for a typescript project
2. See error

**Expected behavior**
Should install

**Comment by davidhu2000** [comment]
looks like you have a typo in the install? 

```diff
- npm install react-spinner
+ npm install react-spinners
```

also, this package supply it's own types so no need to install @type package
