### ISSUE TITLE
PropagateLoader is not showing any loader animation

### ISSUE THREAD

**Issue by nidhi99verma** [davidhu2000/react-spinners#459]
**Describe the bug**
PropagateLoader is not showing any loader animation.

**To Reproduce**

1. Go to IDE install react-spinners
2. Import PropagateLoader
3. Check on the terminal, it is not showing any error but on the browser, it is not showing any loader

**Expected behavior**
It should show PropagateLoader, which is showing on https://www.davidhu.io/react-spinners/ this website 

**Screenshots**
![Screenshot (479)](https://user-images.githubusercontent.com/20599899/147200201-22b37909-6604-479e-8f60-1469416f68da.png)
![Screenshot (480)](https://user-images.githubusercontent.com/20599899/147200218-484a9b94-e583-4ddb-8006-8a37c0de7692.png)

**Comment by AkshayMathurr** [comment]
Hi @nidhi99verma 
Can you elaborate and put the entire code as to why is it causing the loader not to be displayed for you?
I have tried using the `PropagateLoader` and it is being displayed for me.

**Comment by davidhu2000** [comment]
this is working for me too.
