### ISSUE TITLE
Server Side rendering and domkit dependency

### ISSUE THREAD

**Issue by GuillaumeCisco** [davidhu2000/react-spinners#5]
Hello,

Using domkit prevents react-spinners to be used with Server side rendering technics, as domkit needs the document javascript global which is not present on the server.
Should it be possible to get rid of domkit ?

**Comment by davidhu2000** [comment]
I agree that domkit has these limitations. However, I have yet to find a good alternative. Do you have any suggestions?

**Comment by saeedjalali1** [comment]
1+

**Comment by GuillaumeCisco** [comment]
Don't use domkit?
Just inlined css?

**Comment by GuillaumeCisco** [comment]
I was looking about https://github.com/tkh44/emotion, I'm messing around with it. Seems an excellent alternative.

**Comment by GuillaumeCisco** [comment]
I've come with two ways to do it correctly.
Take for example the code for the pulseLoader (115 lines of codes) : https://github.com/davidhu2000/react-spinners/blob/master/src/spinners/PulseLoader.jsx

You achieve SSR support without third parties libraries with this code (67 loc):
```javascript
import React from 'react';
import PropTypes from 'prop-types';

class Loader extends React.Component {
    state = {
        name: 'pulseLoader',
    };
    constructor(props) {
        super(props);

        // don't break on server side rendering
        if (typeof document !== 'undefined') {
            let styleSheet = document.styleSheets[0];

            // do not readd if already added
            if (!Object.keys(styleSheet.cssRules).filter(o => styleSheet.cssRules[o].name === name).length) {
                let keyframes = `@keyframes ${this.state.name} {
                    0% {transform: scale(1);opacity: 1} 
                    45% {transform: scale(0.1);opacity: 0.7}
                    80% {transform: scale(1);opacity: 1}
                }`;

                styleSheet.insertRule(keyframes, styleSheet.cssRules.length);
            }
        }
    }

    style = (i) => ({
        backgroundColor: this.props.color,
        width: this.props.size,
        height: this.props.size,
        margin: this.props.margin,
        borderRadius: '100%',
        display: 'inline-block',
        animation: `${this.state.name} 0.75s ${i * 0.12}s infinite cubic-bezier(.2,.68,.18,1.08)`,
        animationFillMode: 'both',
    });

    a = this.style(1);
    b = this.style(2);
    c = this.style(3);

    render() {
        return this.props.loading ?
            <div>
                <div style={this.a}/>
                <div style={this.b}/>
                <div style={this.c}/>
            </div> : null;
    }
}

Loader.propTypes = {
    loading: PropTypes.bool,
    color: PropTypes.string,
    size: PropTypes.number,
    margin: PropTypes.number,
};

Loader.defaultProps = {
    loading: true,
    color: '#000000',
    size: 15,
    margin: 2,
};

export default Loader;
```

Or with emotion, I suggest would be clearly better as it supports SSR by philosophy (53 loc):
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import {keyframes, css} from 'emotion';
import {onlyUpdateForKeys} from 'recompose';

// This returns an animation
const pulseLoader = keyframes`
  0% {transform: scale(1);opacity: 1} 
  45% {transform: scale(0.1);opacity: 0.7}
  80% {transform: scale(1);opacity: 1}
`;

class Loader extends React.Component {
    style = i => css`{
        background-color: ${this.props.color};
        width: ${this.props.size}px;
        height: ${this.props.size}px;
        margin: ${this.props.margin};
        border-radius: 100%;
        display: inline-block;
        animation: ${pulseLoader} 0.75s ${i * 0.12}s infinite cubic-bezier(.2,.68,.18,1.08);
        animation-fill-mode: both;
    }`;

    a = this.style(1);
    b = this.style(2);
    c = this.style(3);

    render() {
        return this.props.loading ?
            <div>
                <div className={this.a}/>
                <div className={this.b}/>
                <div className={this.c}/>
            </div> : null;
    }
}

Loader.propTypes = {
    loading: PropTypes.bool,
    color: PropTypes.string,
    size: PropTypes.number,
    margin: PropTypes.string,
};

Loader.defaultProps = {
    loading: true,
    color: '#000000',
    size: '15',
    margin: '2px',
};

export default onlyUpdateForKeys(['loading'])(Loader);
```

Thoughts?

**Comment by GuillaumeCisco** [comment]
I've just created the equivalent for the `barLoader`:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import {keyframes, css} from 'emotion';
import {onlyUpdateForKeys} from 'recompose';
import {calculateRgba} from './helpers';

const long = keyframes`
  0% {left: -35%;right: 100%} 
  60% {left: 100%;right: -90%}
  100% {left: 100%;right: -90%}
`;

const short = keyframes`
  0% {left: -200%;right: 100%} 
  60% {left: 107%;right: -8%}
  100% {left: 107%;right: -8%}
`;

class Loader extends React.Component {
    style = i => css`{
        position: absolute;
        height: ${this.props.height}px;
        overflow: hidden;
        background-color: ${this.props.color};
        background-clip: padding-box;
        display: block;
        border-radius: 2px;
        will-change: left, right;
        animation-fill-mode: forwards;
        animation: ${i === 1 ? long : short} 2.1s ${i === 2 ? '1.15s' : ''} ${i === 1 ? 'cubic-bezier(0.65, 0.815, 0.735, 0.395)' : 'cubic-bezier(0.165, 0.84, 0.44, 1)'} infinite;
    }`;

    wrapper = css`{
        width: ${this.props.width}px;
        position: relative;
        height: ${this.props.height}px;
        overflow: hidden;
        background-color: ${calculateRgba(this.props.color, 0.2)};
        background-clip: padding-box;
    }`;

    a = this.wrapper;
    b = this.style(1);
    c = this.style(2);

    render() {
        return this.props.loading ?
            <div>
                <div className={this.a}>
                    <div className={this.b}/>
                    <div className={this.c}/>
                </div>
            </div> : null;
    }
}

Loader.propTypes = {
    loading: PropTypes.bool,
    color: PropTypes.string,
    width: PropTypes.number,
    height: PropTypes.number,
};

Loader.defaultProps = {
    loading: true,
    color: '#000000',
    width: 100,
    height: 4,
};

export default onlyUpdateForKeys('loading')(Loader);
```

Maybe I'll create a repo with all the updated spinners for supporting SSR using emotion.

**Comment by davidhu2000** [comment]
@GuillaumeCisco thank you very much. I will take a closer look when I get a chance, but this looks very promising.

**Comment by GuillaumeCisco** [comment]
Hey @davidhu2000, I've just ported every loader with emotion for supporting SSR.
You can check the PR here https://github.com/davidhu2000/react-spinners/pull/6
Only problem, it does not pass test because of flow, and I need help about this.

I'd be happy to discuss about it.

**Comment by hdngr** [comment]
Hey guys - quick fix on this - either use my fork of domkit as dependency: https://github.com/hdngr/domkit

Or get this PR merged https://github.com/yuanyan/domkit/pull/7

Thanks!

**Comment by davidhu2000** [comment]
@hdngr, thanks for the suggestion. we are currently looking to replace `domkit` with `emotion`, but I will keep your comment as a possible option.

**Comment by isaachinman** [comment]
Just wanted to say I came across this SSR-breakage and will be moving along from the project. People use React in a server environment extremely frequently these days.

**Comment by davidhu2000** [comment]
@isaachinman, we have a PR #6 open to fix SSR, I've been a little busy lately, but I will be reviewing it soon.

**Comment by GuillaumeCisco** [comment]
Hey @davidhu2000, it would be great if you could review it asap.
We are already using it in production in our company ;)

I think the README should be updated for letting people know the babel plugin emotion need to be added to the .babelrc file (or the overrided plugins in the webpack configuration).
@isaachinman I'm curious to know how you figured it out. Can you please share it with us.

**Comment by isaachinman** [comment]
@GuillaumeCisco I didn't, I very quickly did an `npm uninstall`. A CSS loader shouldn't break SSR! Sounds like it'll be fixed soon.

**Comment by davidhu2000** [comment]
@GuillaumeCisco absolutely, I will get to it this weekend. 

Just out of curiosity, how would you guys test the SSR? I don't have a lot of experiences with it. I know you can create a webpack config for SSR.

**Comment by isaachinman** [comment]
@davidhu2000 Try to compile your React tree to a string (for example) in a Node environment. If my understanding is correct, you've elected to use a CSS-in-JS solution that directly references the document (which doesn't exist in SSR). Just find a CSS solution that works in SSR.

**Comment by davidhu2000** [comment]
SSR is fixed via #6

**Comment by davidhu2000** [comment]
@GuillaumeCisco #6 has been merged and published to npm as `v0.1.0`. Can you also verify that SSR works properly?

**Comment by GuillaumeCisco** [comment]
@davidhu2000 yep it works perfectly thanks to emotion.
As I said before I'm using this code in production with SSR :)
You can also test it with the redux first router demo: https://github.com/faceyspacey/redux-first-router-demo

Thnaks!

**Comment by davidhu2000** [comment]
@GuillaumeCisco perfect. I just want someone to verify as well. I tested SSR locally and it was working perfectly. 

Great, closing this issue.

**Comment by GuillaumeCisco** [comment]
Great @davidhu2000 !
I think one last thing is to update the README. Margin is now a string.
Also, feel free to add me as a contributor of this lib. A lot of code has been refactored.

**Comment by davidhu2000** [comment]
@GuillaumeCisco readme is updated. And I added you to `contributors` in `package.json`. Thank you so much for your contributions.
