### ISSUE TITLE
Allow for React 18 > 

### ISSUE THREAD

**Issue by bearsworth** [davidhu2000/react-spinners#516]
**Is your feature request related to a problem? Please describe.**
I believe this package won't work for React 18 and greater. Here is the issue:

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^17.0.0" from react-spinners@0.11.0
npm ERR! node_modules/react-spinners
npm ERR!   react-spinners@"^0.11.0" from the root project

**Describe the solution you'd like**
If possible, allow for React 18, this is a great and easy to use spinner. Would love to be able to use it in newer projects. 

**Describe alternatives you've considered**

**Additional context**

**Comment by bearsworth** [comment]
I have used --legacy-peer-deps which seems to work.

**Comment by davidhu2000** [comment]
@bearsworth please update to 0.12.0 which includes react 18 support

**Comment by bearsworth** [comment]
@davidhu2000 Thanks for that and thanks for this awesome package man.
