### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by ioanlucut** [davidhu2000/react-spinners#522]
Hey!

Thanks a lot for this lib and for implementing the feature I've requested for a long time (in alpha now).

I have a different issue now: since we use SSR, this [bit](https://github.com/davidhu2000/react-spinners/blob/main/src/PulseLoader.tsx#L7-L11) is called [asap](https://github.com/davidhu2000/react-spinners/blob/main/src/helpers/animation.ts#L2).

Can we defer it to the client-side only? Or better said, not running it on the server-side?
For some reason, we did not have this issue so far.

**Comment by davidhu2000** [comment]
Does the code run on server side? Mt understanding is that document does not exist server side? 

I'm not 100% on how to figure out server vs client side tho

**Comment by davidhu2000** [comment]
i was able to reproduce this using nextjs, is this similar to the issue you have? 

<img width="490" alt="Screen Shot 2022-06-04 at 5 45 31 PM" src="https://user-images.githubusercontent.com/15827041/172030269-04cc0cdc-0bdf-4a29-b6c9-fbebd681f56b.png">

**Comment by davidhu2000** [comment]
@ioanlucut can you give `0.13.0-beta.4` a try?

**Comment by davidhu2000** [comment]
<img width="144" alt="Screen Shot 2022-06-04 at 6 10 47 PM" src="https://user-images.githubusercontent.com/15827041/172030757-57b50385-a7eb-4d6b-bea8-9ea445d3cb83.png">
<img width="122" alt="Screen Shot 2022-06-04 at 6 10 57 PM" src="https://user-images.githubusercontent.com/15827041/172030758-fdaeb794-7ff4-4442-aa7e-c4e28da04b91.png">

tested via NextJS, with js off and on, seems like it's working

**Comment by ioanlucut** [comment]
Thanks a lot!
