### ISSUE TITLE
PuffLoader broken

### ISSUE THREAD

**Issue by sgehrman** [davidhu2000/react-spinners#528]
"react-spinners": "^0.13.2",

Puffloader has a thick border for the first animation loop, then gets thin

It worked fine in this version:
    "react-spinners": "^0.12.0",

I just updated packages and noticed the bug. I reverted back to .12.

**Comment by sgehrman** [comment]
bug appears on this page too https://www.davidhu.io/react-spinners/

**Comment by davidhu2000** [comment]
this is fixed in 0.13.3
