### ISSUE TITLE
Issue with positioning the spinner in center.

### ISSUE THREAD

**Issue by Suguru-Tokuda** [davidhu2000/react-spinners#53]
**Do you want to request a feature or report a bug?**
No

**If reporting a bug, what version of `react-spinners` are you currently using?**

**What is the current behavior?**
I want to position the spinner horizontally and vertically center inside <div className="col-sm-9 col-md-9"></div>. I tried both "text-align: center" and "text-center" but neither of them worked.

**If the current behavior is a bug, please provide the steps to reproduce**

**Comment by davidhu2000** [comment]
can you provide some sample code on what you did?

**Comment by krlmazanik** [comment]
@Suguru-Tokuda Hello. Try this:
`import { ClipLoader } from "react-spinners";
import React from "react";

const Spinner = props => {
 const style = {textAlign: 'center'};
  return (
    <div style={style}>
      <ClipLoader color={"#123abc"} loading={props.isFetching} />
    </div>
  );
};

export default Spinner;
`

If u want to position in the very middle of the screen, try this:
` const style = {
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)"
  };`

Hope this will help!

**Comment by piyali007** [comment]
@krlmazanik  thanx it works

**Comment by abcFearey** [comment]
@krlmazanik Thanks a lot!

**Comment by hoangou01** [comment]
Thanks a lot!

**Comment by shermuhammadkhan** [comment]
The above css is not the good way of doing it manually as Bootstrap has its own classes I think. use 
**d-flex justify-content-center** in the parent div of the Spinner and it will center it in its parent div. For Reference have a look at the link: 
https://getbootstrap.com/docs/4.3/components/spinners/
