### ISSUE TITLE
Prop `style` did not match

### ISSUE THREAD

**Issue by liby** [davidhu2000/react-spinners#531]
**Package Version**
`0.13.3`

**Describe the bug**

When used with Next.js, the console sees the following error:
> Warning: Prop `style` did not match. Server: "position:absolute;top:50%;left:50%;display:block;width:10px;height:10px;border-radius:5px;transform:translate(-50%, -50%);animation-fill-mode:none;animation:react-spinners-HashLoader-before 2s infinite" Client: "position:absolute;content:;top:50%;left:50%;display:block;width:10px;height:10px;border-radius:5px;transform:translate(-50%, -50%);animation-fill-mode:none;animation:react-spinners-HashLoader-before 2s infinite"

**To Reproduce**
1. Clone this [repo](https://github.com/liby/neptune/tree/feature/show-loading-state)
2. `git switch feature/show-loading-state`
3. `pnpm install`
4. `pnpm dev` 

**Expected behavior**

No error.

**Screenshots**

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/38807139/180936349-736d746e-3a21-4611-9cdc-607ea97612de.png">

**Additional context**

n/a

**Comment by davidhu2000** [comment]
@liby can you try 0.13.4 and see if the issue is fixed?

**Comment by liby** [comment]
It works. Thanks.
