### ISSUE TITLE
beat_loader.js(x)

### ISSUE THREAD

**Issue by rwb196884** [davidhu2000/react-spinners#563]
**Package Version**

1.0.0

**Describe the bug**

```
Module not found: Error: Can't resolve './beat_loader.jsx' in 'C:\Work\blah\client\node_modules\react-spinners\dist\spinners'
```

**To Reproduce**
```
> yarn run build
```

**Screenshots**

![image](https://user-images.githubusercontent.com/12090617/223763087-49f82f90-f7fd-4417-bc6e-0a10aa0105d6.png)

The file is `beat_loader.js` not `beat_loader.jsx`.

**Expected behavior**

It compiles.

**Comment by davidhu2000** [comment]
so i incorrectly published 1.0.0 when i initially started this package. I tried to unpublish it but it was no longer possible so I deprecated it instead. 

https://www.npmjs.com/package/react-spinners/v/1.0.0

you can see here https://www.npmjs.com/package/react-spinners?activeTab=versions that the latest version is 0.13.8
