### ISSUE TITLE
NextJS 13 doesn't render SSR

### ISSUE THREAD

**Issue by allenchuang** [davidhu2000/react-spinners#565]
While experimenting with NextJS 13, and playing around with React `<Suspense/>` I realized that the animation for all `react-spinners` components are not working.

```
<Suspense fallback={<BarLoader color="#36d7b7" />}>
    <SSRLoadedComponent />
</Suspense>

```

**Comment by codewizard-dt** [comment]
Very sad to run into this issue.  I am migrating our app to SSR and none of these are working.  I love these spinners and I would be sad to lose them
