### ISSUE TITLE
How to customize animation???

### ISSUE THREAD

**Issue by CaptainIvan** [davidhu2000/react-spinners#58]
**Do you want to request a feature or report a bug?**
Yes, css from @emotion/core doesn't work. 

**If reporting a bug, what version of `react-spinners` are you currently using?**
last

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/25664253/53940307-655ff300-40c6-11e9-9f8a-c19b879816df.png)

**If the current behavior is a bug, please provide the steps to reproduce**
I don't know why. But it's a problem. @emotions/core doesn't work with your component. And I can't change animation. How I can rebuild module?

**Comment by CaptainIvan** [comment]
I just want to change scale to 1.0. But it's doesn't work
![image](https://user-images.githubusercontent.com/25664253/53940386-a22bea00-40c6-11e9-9d00-ee5c833070ad.png)
![image](https://user-images.githubusercontent.com/25664253/53940408-af48d900-40c6-11e9-8425-0e3993071576.png)

**Comment by davidhu2000** [comment]
This issue is resolved. please update to v0.6.0
