### ISSUE TITLE
Proposal for Implementing Search Filters on React Spinners

### ISSUE THREAD

**Issue by 0rigin-c0de** [davidhu2000/react-spinners#580]
**Is your feature request related to a problem? Please describe.**

Finding specific loaders on the React Spinners website can be challenging and time-consuming, especially when a large collection of loaders is available. Users may become frustrated when they manually scroll through the list to locate the needed loader.

**Describe the solution you'd like**

I would like to propose adding a search filter to the React Spinners website, allowing users to quickly search for loaders based on keywords or tags. This search functionality would greatly enhance the user experience by enabling visitors to find the desired loader more efficiently.

**Describe alternatives you've considered**

An alternative solution could be implementing a tagging system for the loaders, where each loader is tagged with relevant keywords. However, a search filter would likely be more intuitive and user-friendly.

**Additional context**
Introducing a search filter would not only improve user satisfaction but also encourage more users to explore and utilize the wide range of loaders available on the React Spinners website. Additionally, this feature could potentially attract new users who prioritize ease of navigation and searchability in web development resources.
We can search very clearly if we have a nice search bar with a good UI.

**Comment by davidhu2000** [comment]
thanks for the proposal, but searching doesn't seem necessary given there's ~20 loaders, plus, it's better to be able to see the rendered output instead of search by name.
