### ISSUE TITLE
MoonLoader wobbles when provided a size not evenly divisible by 7

### ISSUE THREAD

**Issue by RigoOnRails** [davidhu2000/react-spinners#583]
**Package Version**
0.13.4

**Describe the bug**
The `MoonLoader` component does some math internally to compute the correct border width for the spinner + the overall container size. The magic number here seems to be `7`.

https://github.com/davidhu2000/react-spinners/blob/ddbcf239208a1bae07e276159fcdff3aa6090e5e/src/MoonLoader.tsx#L18

When provided a size that is evenly divisible by 7 (Eg. 14, 21, 28, etc.), the component renders perfectly & doesn't wobble, due to the perfect whole numbers in the computed sizes:

<img width="709" alt="Capture d’écran 2024-03-18 à 17 52 40" src="https://github.com/davidhu2000/react-spinners/assets/17030877/32a0c9cd-f59f-418d-8cf6-993bdc238b2d">

But when you provide an arbitrary size like 24, you get these very specific sizes that start causing the wobbling, I assume due to the browser engine:

<img width="693" alt="Capture d’écran 2024-03-18 à 17 56 08" src="https://github.com/davidhu2000/react-spinners/assets/17030877/757a46b3-fdad-4fa9-a0c5-c6a54f77adf9">

**To Reproduce**
Provide a size not evenly divisible by 7.

**Expected behavior**
The component should be stable, no matter the size provided.

**Additional context**
This is tested using Chrome on macOS.

**Comment by davidhu2000** [comment]
we could just do

```ts
const moonSize = Math.round(value / 7);
```

but that could mean the final size won't exactly be right
