### ISSUE TITLE
Bundling Failed Error

### ISSUE THREAD

**Issue by velhari** [davidhu2000/react-spinners#59]
**Do you want to request a feature or report a bug?** Bug

**If reporting a bug, what version of `react-spinners` are you currently using?**
0.5.3

**What is the current behavior?**
Getting Bundling Failed Error

**If the current behavior is a bug, please provide the steps to reproduce**
I Installed react-spinners using npm install --save react-spinners and added below lines in .babelrc file {
  "presets": ["react", "env"],
  "plugins": ["emotion"]
}
getting bundling failed error

this is the error i am getting
"bundling failed: Error: While trying to resolve module `react-spinners` from file `/ReactNative/NoteList.js`, the package `/ReactNative/node_modules/react-spinners/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/ReactNative/node_modules/react-spinners/dist/index.js`. Indeed, none of these files exist"

**Comment by davidhu2000** [comment]
@velhari I'm fairly certain this package will NOT work for React Native.
