### ISSUE TITLE
Support importing specific loader with TypeScript

### ISSUE THREAD

**Issue by andrew-humu** [davidhu2000/react-spinners#60]
**Do you want to request a feature or report a bug?**
Feature

**If reporting a bug, what version of `react-spinners` are you currently using?**
`v0.4.5`

**What is the current behavior?**
This is an extension of issue #23.

It would be awesome to also support the loading of individual packages via TypeScript.

See also, this comment: https://github.com/davidhu2000/react-spinners/issues/23#issuecomment-468675074

**Comment by echee** [comment]
for this to work, don't you just need to generate type files in the root? or better yet, add the types to DefinitelyTyped?

**Comment by davidhu2000** [comment]
@echee yeah, each file would need their own typing file. This is part of the `v0.6.0` release, where the entire package is now in typescript. can you try `npm install react-spinners@0.6.0-alpha.3` and see if this works?

**Comment by davidhu2000** [comment]
This feature is supported in `v0.6.0`
