### ISSUE TITLE
Update peer dependencies to support React 19

### ISSUE THREAD

**Issue by mobeigi** [davidhu2000/react-spinners#611]
Currently we have:
```
  "peerDependencies": {
    "react": "^16.0.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.0.0 || ^17.0.0 || ^18.0.0"
  },
```

React 19 is currently in RC and release is around the corner.

Could we update the `react` peer dependencies to support `19.0.0`?

From my inspection, it doesn't look like this project using any functionality that will change / break from `18` to `19` so I believe the change can be made now.

Also I'm personally using this project on production with React 19 RC with no issues.

**Comment by rob212** [comment]
Any updates on when/if this is getting merged?
