### ISSUE TITLE
Animation Speed

### ISSUE THREAD

**Issue by brightsider** [davidhu2000/react-spinners#63]
How yo change speed of animation?

**Comment by davidhu2000** [comment]
Here is an example. also, please update to v0.6.0 style override has a bug before. 


![image](https://user-images.githubusercontent.com/25664253/53940386-a22bea00-40c6-11e9-9d00-ee5c833070ad.png)
![image](https://user-images.githubusercontent.com/25664253/53940408-af48d900-40c6-11e9-8425-0e3993071576.png)

_Originally posted by @CaptainIvan in https://github.com/davidhu2000/react-spinners/issues/58#issuecomment-470421698_
