### ISSUE TITLE
Can't resolve './beat_loader.jsx'

### ISSUE THREAD

**Issue by roshan605** [davidhu2000/react-spinners#65]
**Do you want to request a feature or report a bug?**
bug

**If reporting a bug, what version of `react-spinners` are you currently using?**
"react-spinners": "1.0.0",

**What is the current behavior?**
does not work. Can't resolve './beat_loader.jsx'

**If the current behavior is a bug, please provide the steps to reproduce**
![image](https://user-images.githubusercontent.com/20854187/56961616-d2957f00-6b71-11e9-9a8b-142983755f7b.png)

**Comment by davidhu2000** [comment]
@roshan605 how did you install? version `1.0.0` is the incorrect version, `0.5.4` is the latest

**Comment by wKovacs64** [comment]
Was 1.0.0 published by mistake? It's available on npm and missing a ton of stuff.

**Comment by davidhu2000** [comment]
yes. and it was deprecated. the latest version is 0.5.12

**Comment by wKovacs64** [comment]
Ah okay. Got an automated PR for it, for some reason. Thanks.
