### ISSUE TITLE
Warning in using FadeLoader.

### ISSUE THREAD

**Issue by JagdishUpadhyay** [davidhu2000/react-spinners#7]
Failed prop type: Invalid prop `margin` of type `string` supplied to `Loader`, expected `number`.

**Comment by GuillaumeCisco** [comment]
Will be soon fixed when PR #6 will be merged ;)

**Comment by davidhu2000** [comment]
#6 is merged, so this issue is resolved.

**Comment by JagdishUpadhyay** [comment]
Now, after updating this error is coming
Module not found: Error: Cannot resolve module 'recompose'

**Comment by GuillaumeCisco** [comment]
Looks like the dependency `recompose` is missing here.
Did you install the very last version of react-spinners ? The package.json includes it.
If you want to quickly fix this issue, please run `npm install --save recompose`

**Comment by JagdishUpadhyay** [comment]
I have installed the latest version(0.1.2). Yeah, package.json have recompose included. I don't know why it is not installing on my machine. BTW, I am using windows system.
