### ISSUE TITLE
HashLoader color prop not working

### ISSUE THREAD

**Issue by Samuel-Montoya** [davidhu2000/react-spinners#75]
**Describe the bug**
When using the HashLoader, the color prop makes it not appear.

**To Reproduce**
1. Import { HashLoader }
2. `<HashLoader color='red' />`
3. No Result
4. However, `<HashLoader />` renders in black.

**Expected behavior**
It should pull in the color, but nothing renders.

**Comment by davidhu2000** [comment]
can you try the hash code for red instead?

**Comment by davidhu2000** [comment]
I have figured this out. Made an update in `v0.6.0-alpha.8` to allow `<HashLoader color='red' />`. Only the basic colors are supported though.

**Comment by davidhu2000** [comment]
This has been fixed in `v0.6.0`
