### ISSUE TITLE
unable to use package with webpack + next.js

### ISSUE THREAD

**Issue by 0x13a** [davidhu2000/react-spinners#76]
using nextjs and webpack after installing can't seem to make it work

import BarLoaderComponent from "./BarLoader";
       ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19

I don't have babel, how does this work with webpack?

**Comment by davidhu2000** [comment]
@0x13a what version are you using? There seems to be an issue with 0.5.13. try downgrading to 0.5.12

**Comment by 0x13a** [comment]
Not sure about the version - I've migrated to `react-spinners-kit`

**Comment by YarochkinMichael** [comment]
I have the same problem

**Comment by YarochkinMichael** [comment]
removing folder "dist" from 0.5.13 is solving problem

**Comment by KiyaDoig** [comment]
Is this being worked on? I have the same issue.

**Comment by davidhu2000** [comment]
yes. This issue will be resolved in `v0.6.0`. That is currently in the alpha stage right now. 

You can use `v0.5.12` in the meantime.
